version: "3.9"

services:
  # Flask API
  flask:
    build: ./flask-api
    container_name: flask-api
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5001
      - DATABASE_URL=postgresql://postgres:PSGRdb0723%3B@host.docker.internal:5432/warehouse
    ports:
      - "5001:5001"
    depends_on:
      - laravel
    networks:
      - app-net

  # Laravel backend (PHP-FPM)
  laravel:
    build: ./laravel-backend
    container_name: laravel-backend
    volumes:
      - ./laravel-backend:/var/www/html
    networks:
      - app-net

  # Nginx for Laravel
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel-backend:/var/www/html
      - ./laravel-backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-net

  # Next.js frontend
  nextjs:
    build: ./frontend-nextjs
    container_name: frontend-nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api
    depends_on:
      - nginx
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
